formatter:
  bento.formatter.Stylish: {}
tools:
  r2c.eslint:
    ignore:
    - react/jsx-space-before-closing
    - import/exports-last
    - max-params
    - jsx-a11y/no-access-key
    - jsx-a11y/no-distracting-elements
    - operator-assignment
    - react/destructuring-assignment
    - react/no-children-prop
    - prefer-destructuring
    - react/forbid-foreign-prop-types
    - react/prefer-read-only-props
    - react/react-in-jsx-scope
    - consistent-this
    - key-spacing
    - jsx-a11y/no-autofocus
    - react/jsx-sort-props
    - implicit-arrow-linebreak
    - comma-spacing
    - object-curly-spacing
    - lines-around-comment
    - react/sort-comp
    - sort-keys
    - jsx-a11y/no-onchange
    - jsx-a11y/iframe-has-title
    - react/static-property-placement
    - import/dynamic-import-chunkname
    - prefer-spread
    - multiline-comment-style
    - block-spacing
    - no-multi-assign
    - jsx-a11y/no-noninteractive-element-interactions
    - react/jsx-equals-spacing
    - eol-last
    - func-name-matching
    - no-cond-assign
    - react/sort-prop-types
    - wrap-regex
    - new-cap
    - multiline-ternary
    - react/default-props-match-prop-types
    - import/max-dependencies
    - react/jsx-no-literals
    - max-lines
    - no-lonely-if
    - prefer-reflect
    - array-bracket-newline
    - max-statements-per-line
    - arrow-parens
    - jsx-a11y/aria-activedescendant-has-tabindex
    - import/no-namespace
    - prefer-numeric-literals
    - no-return-assign
    - import/first
    - react/jsx-key
    - react/jsx-boolean-value
    - max-depth
    - jsx-a11y/html-has-lang
    - jsx-a11y/media-has-caption
    - import/no-anonymous-default-export
    - prefer-rest-params
    - react/boolean-prop-naming
    - no-ternary
    - react/jsx-handler-names
    - jsx-a11y/label-has-associated-control
    - camelcase
    - id-match
    - jsx-a11y/interactive-supports-focus
    - prefer-named-capture-group
    - semi
    - space-unary-ops
    - jsx-a11y/mouse-events-have-key-events
    - react/forbid-dom-props
    - curly
    - prefer-object-spread
    - jsx-a11y/click-events-have-key-events
    - react/jsx-filename-extension
    - react/forbid-prop-types
    - no-trailing-spaces
    - react/forbid-elements
    - array-bracket-spacing
    - max-nested-callbacks
    - padding-line-between-statements
    - react/jsx-indent-props
    - function-call-argument-newline
    - capitalized-comments
    - jsx-a11y/no-static-element-interactions
    - no-unneeded-ternary
    - one-var
    - max-statements
    - no-mixed-spaces-and-tabs
    - react/no-find-dom-node
    - react/jsx-sort-prop-types
    - no-mixed-operators
    - unicode-bom
    - function-paren-newline
    - import/extensions
    - no-tabs
    - react/jsx-max-depth
    - react/jsx-one-expression-per-line
    - space-before-blocks
    - func-names
    - switch-colon-spacing
    - react/prop-types
    - react/no-string-refs
    - react/jsx-closing-tag-location
    - jsx-a11y/scope
    - no-nested-ternary
    - id-length
    - react/jsx-wrap-multilines
    - prefer-const
    - react/self-closing-comp
    - line-comment-position
    - one-var-declaration-per-line
    - react/jsx-fragments
    - react/prefer-es6-class
    - template-tag-spacing
    - jsx-a11y/no-redundant-roles
    - spaced-comment
    - import/no-named-default
    - prefer-arrow-callback
    - react/jsx-props-no-spreading
    - react/no-redundant-should-component-update
    - react/jsx-closing-bracket-location
    - no-multiple-empty-lines
    - keyword-spacing
    - react/jsx-curly-newline
    - operator-linebreak
    - react/no-set-state
    - space-in-parens
    - no-plusplus
    - sort-vars
    - jsx-a11y/no-noninteractive-tabindex
    - max-lines-per-function
    - no-console
    - brace-style
    - import/no-unassigned-import
    - react/forbid-component-props
    - no-case-declarations
    - array-element-newline
    - prefer-template
    - import/newline-after-import
    - comma-dangle
    - react/jsx-curly-brace-presence
    - comma-style
    - react/jsx-pascal-case
    - quotes
    - no-underscore-dangle
    - react/require-default-props
    - no-inline-comments
    - newline-per-chained-call
    - jsx-a11y/tabindex-no-positive
    - max-len
    - react/no-unknown-property
    - id-blacklist
    - import/no-named-export
    - react/display-name
    - jsx-a11y/anchor-has-content
    - new-parens
    - no-restricted-syntax
    - no-whitespace-before-property
    - react/jsx-sort-default-props
    - import/group-exports
    - linebreak-style
    - react/no-multi-comp
    - react/state-in-constructor
    - react/style-prop-object
    - import/no-default-export
    - no-bitwise
    - computed-property-spacing
    - lines-between-class-members
    - react/jsx-tag-spacing
    - semi-style
    - import/no-duplicates
    - react/prefer-stateless-function
    - import/order
    - nonblock-statement-body-position
    - react/jsx-max-props-per-line
    - jsx-a11y/alt-text
    - react/jsx-curly-spacing
    - semi-spacing
    - no-array-constructor
    - object-property-newline
    - react/jsx-props-no-multi-spaces
    - strict
    - react/jsx-indent
    - jsx-quotes
    - func-call-spacing
    - no-continue
    - space-before-function-paren
    - space-infix-ops
    - jsx-a11y/img-redundant-alt
    - prefer-promise-reject-errors
    - padded-blocks
    - quote-props
    - indent
    - react/button-has-type
    - func-style
    - react/require-optimization
    - no-negated-condition
    - import/prefer-default-export
    - object-curly-newline
    - no-new-object
  r2c.flake8:
    ignore:
    - E101
    - E111
    - E114
    - E115
    - E116
    - E121
    - E122
    - E123
    - E124
    - E125
    - E126
    - E127
    - E128
    - E129
    - E131
    - E133
    - E201
    - E202
    - E203
    - E211
    - E221
    - E222
    - E223
    - E224
    - E225
    - E226
    - E227
    - E228
    - E231
    - E241
    - E242
    - E251
    - E261
    - E262
    - E265
    - E266
    - E271
    - E272
    - E273
    - E274
    - E275
    - E301
    - E302
    - E303
    - E304
    - E305
    - E401
    - E402
    - E501
    - E502
    - E701
    - E702
    - E703
    - E704
    - E711
    - E712
    - E713
    - E714
    - E721
    - E731
    - E741
    - E742
    - E743
    - W191
    - W291
    - W292
    - W293
    - W391
    - W503
    - W504
    - F406
