formatter:
  bento.formatter.Stylish: {}
tools:
  r2c.eslint:
    ignore:
    - max-statements
    - jsx-a11y/scope
    - react/jsx-indent-props
    - new-parens
    - jsx-a11y/no-redundant-roles
    - function-paren-newline
    - react/jsx-tag-spacing
    - import/no-duplicates
    - sort-keys
    - prefer-rest-params
    - react/forbid-component-props
    - react/prefer-stateless-function
    - no-underscore-dangle
    - one-var
    - no-tabs
    - comma-dangle
    - import/first
    - jsx-a11y/no-static-element-interactions
    - dot-location
    - jsx-a11y/no-noninteractive-tabindex
    - array-bracket-spacing
    - key-spacing
    - func-names
    - quote-props
    - react/button-has-type
    - prefer-destructuring
    - wrap-regex
    - react/forbid-elements
    - yoda
    - react/jsx-curly-brace-presence
    - react/jsx-sort-props
    - react/react-in-jsx-scope
    - max-nested-callbacks
    - react/default-props-match-prop-types
    - jsx-a11y/html-has-lang
    - consistent-this
    - keyword-spacing
    - jsx-a11y/no-distracting-elements
    - no-labels
    - unicode-bom
    - import/no-named-default
    - function-call-argument-newline
    - comma-spacing
    - jsx-a11y/label-has-associated-control
    - no-cond-assign
    - prefer-reflect
    - no-lonely-if
    - brace-style
    - prefer-promise-reject-errors
    - jsx-a11y/iframe-has-title
    - class-methods-use-this
    - new-cap
    - consistent-return
    - no-redeclare
    - react/jsx-closing-tag-location
    - eol-last
    - max-params
    - no-multi-spaces
    - max-depth
    - func-style
    - no-nested-ternary
    - react/jsx-indent
    - react/jsx-no-literals
    - no-restricted-syntax
    - react/jsx-handler-names
    - jsx-a11y/media-has-caption
    - id-blacklist
    - prefer-spread
    - react/destructuring-assignment
    - no-inline-comments
    - object-curly-newline
    - react/jsx-key
    - react/forbid-prop-types
    - no-continue
    - jsx-a11y/no-noninteractive-element-interactions
    - jsx-a11y/click-events-have-key-events
    - react/jsx-equals-spacing
    - jsx-a11y/tabindex-no-positive
    - nonblock-statement-body-position
    - jsx-a11y/img-redundant-alt
    - react/no-set-state
    - react/jsx-wrap-multilines
    - react/static-property-placement
    - no-negated-condition
    - react/jsx-max-props-per-line
    - no-bitwise
    - semi
    - import/extensions
    - quotes
    - array-element-newline
    - react/no-unknown-property
    - no-octal
    - react/state-in-constructor
    - jsx-a11y/aria-activedescendant-has-tabindex
    - object-curly-spacing
    - react/jsx-curly-newline
    - react/sort-prop-types
    - no-implicit-globals
    - object-property-newline
    - react/prefer-read-only-props
    - react/no-string-refs
    - max-statements-per-line
    - operator-linebreak
    - prefer-const
    - computed-property-spacing
    - jsx-a11y/anchor-has-content
    - react/jsx-one-expression-per-line
    - react/self-closing-comp
    - jsx-a11y/mouse-events-have-key-events
    - lines-between-class-members
    - jsx-a11y/no-access-key
    - no-whitespace-before-property
    - space-in-parens
    - import/no-named-export
    - lines-around-comment
    - import/order
    - react/require-optimization
    - no-multi-str
    - vars-on-top
    - spaced-comment
    - jsx-a11y/no-autofocus
    - jsx-quotes
    - semi-spacing
    - max-lines-per-function
    - max-classes-per-file
    - semi-style
    - template-tag-spacing
    - react/prefer-es6-class
    - react/display-name
    - no-div-regex
    - id-length
    - implicit-arrow-linebreak
    - import/exports-last
    - jsx-a11y/alt-text
    - react/no-multi-comp
    - block-spacing
    - no-unneeded-ternary
    - react/no-children-prop
    - prefer-template
    - no-multiple-empty-lines
    - space-infix-ops
    - padded-blocks
    - operator-assignment
    - no-fallthrough
    - dot-notation
    - no-mixed-spaces-and-tabs
    - no-else-return
    - no-console
    - react/jsx-max-depth
    - react/jsx-props-no-spreading
    - react/sort-comp
    - no-self-assign
    - no-throw-literal
    - padding-line-between-statements
    - prefer-named-capture-group
    - no-param-reassign
    - react/jsx-boolean-value
    - no-invalid-this
    - prefer-object-spread
    - no-new-object
    - react/jsx-closing-bracket-location
    - arrow-parens
    - react/style-prop-object
    - array-bracket-newline
    - import/no-anonymous-default-export
    - no-trailing-spaces
    - react/boolean-prop-naming
    - space-before-function-paren
    - line-comment-position
    - multiline-comment-style
    - react/jsx-filename-extension
    - newline-per-chained-call
    - no-floating-decimal
    - curly
    - comma-style
    - jsx-a11y/interactive-supports-focus
    - react/jsx-pascal-case
    - react/jsx-sort-default-props
    - import/no-namespace
    - no-script-url
    - react/require-default-props
    - no-empty-function
    - space-unary-ops
    - react/forbid-foreign-prop-types
    - func-call-spacing
    - func-name-matching
    - import/max-dependencies
    - react/jsx-space-before-closing
    - capitalized-comments
    - no-mixed-operators
    - multiline-ternary
    - react/jsx-sort-prop-types
    - space-before-blocks
    - switch-colon-spacing
    - prefer-arrow-callback
    - max-lines
    - linebreak-style
    - no-multi-assign
    - no-self-compare
    - react/jsx-fragments
    - jsx-a11y/no-onchange
    - no-array-constructor
    - strict
    - react/no-find-dom-node
    - react/no-redundant-should-component-update
    - guard-for-in
    - no-return-assign
    - no-ternary
    - react/forbid-dom-props
    - lines-around-directive
    - import/no-unassigned-import
    - camelcase
    - indent
    - id-match
    - import/dynamic-import-chunkname
    - max-len
    - sort-vars
    - prefer-numeric-literals
    - no-case-declarations
    - react/prop-types
    - react/jsx-curly-spacing
    - import/newline-after-import
    - no-void
    - import/no-default-export
    - no-plusplus
    - one-var-declaration-per-line
    - react/jsx-props-no-multi-spaces
    - import/prefer-default-export
    - import/group-exports
    - accessor-pairs
